# Generated by Django 4.2.16 on 2025-09-16 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this form configuration', max_length=200)),
                ('form_type', models.SlugField(help_text="Unique identifier for this form (e.g., 'sales_calls_salescall')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this form is for')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently in use')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for tracking changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout_settings', models.JSONField(default=dict, help_text='Global layout settings like column widths, styling preferences')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_definitions', to=settings.AUTH_USER_MODEL)),
                ('target_model', models.ForeignKey(help_text='The Django model this configuration applies to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Form Configuration',
                'verbose_name_plural': 'Form Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section title displayed in the form', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for this section', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description shown in the section header')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is currently visible')),
                ('is_collapsed', models.BooleanField(default=False, help_text='Whether this section starts collapsed')),
                ('conditional_logic', models.JSONField(blank=True, default=dict, help_text='JSON rules for when this section should be visible')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Permission rules for who can see this section')),
                ('css_classes', models.CharField(blank=True, help_text='Additional CSS classes to apply to this section', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='form_composer.formdefinition')),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'ordering': ['form_definition', 'order', 'name'],
                'unique_together': {('form_definition', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='Model field name or dynamic field identifier', max_length=100)),
                ('label', models.CharField(blank=True, help_text='Custom field label (overrides model field label)', max_length=200)),
                ('help_text', models.TextField(blank=True, help_text='Help text displayed with the field')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for input fields', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field is displayed in the form')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this field is required for form submission')),
                ('is_readonly', models.BooleanField(default=False, help_text='Whether this field is read-only')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the section')),
                ('field_type', models.CharField(choices=[('char', 'Text Field'), ('text', 'Long Text'), ('integer', 'Integer'), ('decimal', 'Decimal Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date & Time'), ('time', 'Time'), ('email', 'Email'), ('url', 'URL'), ('choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('file', 'File'), ('image', 'Image'), ('json', 'JSON Data'), ('foreign_key', 'Foreign Key')], default='char', help_text='Type of field for dynamic fields', max_length=50)),
                ('widget_type', models.CharField(choices=[('default', 'Default Widget'), ('text', 'Text Input'), ('textarea', 'Textarea'), ('number', 'Number Input'), ('email', 'Email Input'), ('url', 'URL Input'), ('password', 'Password Input'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('select', 'Select Dropdown'), ('multiselect', 'Multiple Select'), ('date', 'Date Picker'), ('datetime', 'DateTime Picker'), ('time', 'Time Picker'), ('file', 'File Upload'), ('image', 'Image Upload'), ('hidden', 'Hidden Field')], default='default', help_text='Widget to use for rendering this field', max_length=50)),
                ('widget_attrs', models.JSONField(blank=True, default=dict, help_text="Additional attributes for the widget (e.g., {'rows': 3})")),
                ('choices_source', models.CharField(blank=True, help_text='Source for choice values (JSON array, model method, or callable)', max_length=200)),
                ('choices_data', models.JSONField(blank=True, default=list, help_text="Static choice data as [['key', 'label'], ...] pairs")),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Custom validation rules for this field')),
                ('default_value', models.TextField(blank=True, help_text='Default value for new instances')),
                ('is_dynamic', models.BooleanField(default=False, help_text='Whether this is a custom field not in the model')),
                ('storage_type', models.CharField(choices=[('model_field', 'Store in model field'), ('value_store', 'Store in generic value store'), ('computed', 'Computed/display only')], default='model_field', help_text='How field data is stored', max_length=50)),
                ('css_classes', models.CharField(blank=True, help_text='Additional CSS classes for this field', max_length=200)),
                ('conditional_logic', models.JSONField(blank=True, default=dict, help_text='JSON rules for when this field should be visible/enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configs', to='form_composer.formsection')),
            ],
            options={
                'verbose_name': 'Field Configuration',
                'verbose_name_plural': 'Field Configurations',
                'ordering': ['section', 'order', 'field_key'],
                'unique_together': {('section', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_key', models.CharField(help_text='Unique identifier for this preference type', max_length=100)),
                ('preference_value', models.JSONField(help_text='The preference value (any JSON-serializable data)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_composer_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'unique_together': {('user', 'preference_key')},
            },
        ),
        migrations.CreateModel(
            name='DynamicFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_time', models.TimeField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='dynamic_fields/')),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_composer_values', to='contenttypes.contenttype')),
                ('field_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='form_composer.fieldconfig')),
            ],
            options={
                'verbose_name': 'Dynamic Field Value',
                'verbose_name_plural': 'Dynamic Field Values',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='form_compos_content_34b570_idx')],
                'unique_together': {('field_config', 'content_type', 'object_id')},
            },
        ),
    ]
