# Generated by Django 5.2.6 on 2025-09-12 18:30
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('meeting_subject', models.CharField(choices=[('BRM', 'Business Relationship Management'), ('Negotiations', 'Negotiations'), ('Contract Review', 'Contract Review'), ('Site Inspection', 'Site Inspection'), ('Presentation', 'Presentation'), ('Follow-up', 'Follow-up Meeting'), ('Other', 'Other')], max_length=20)),
                ('business_potential', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('next_steps', models.TextField(help_text='Planned next steps from this meeting')),
                ('detailed_notes', models.TextField(help_text='Detailed notes from the meeting')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, help_text='When to follow up', null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_calls', to='accounts.account')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
