# Generated by Django 5.2.6 on 2025-09-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescall',
            name='visit_date',
            field=models.DateField(db_index=True),
        ),
    ]
