# Generated by Django 5.2.6 on 2025-10-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_calls', '0002_alter_salescall_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescall',
            name='meeting_subject',
            field=models.CharField(choices=[('initial_contact', 'Initial Contact Meeting'), ('follow_up', 'Follow-up Meeting'), ('follow_up_meeting', 'Follow-up Meeting'), ('BRM', 'Business Review Management'), ('relationship_mgmt', 'Relationship Management'), ('sales_presentation', 'Sales Presentation'), ('contract_negotiation', 'Contract Negotiation'), ('site_inspection', 'Site Inspection'), ('client_visit', 'Client Site Visit'), ('proposal_presentation', 'Proposal Presentation'), ('Unknown', 'Unknown')], max_length=50),
        ),
    ]
