# Generated by Django 5.2.6 on 2025-09-12 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company/Organization name', max_length=200)),
                ('account_type', models.CharField(choices=[('Company', 'Company'), ('Government', 'Government'), ('Travel Agency', 'Travel Agency')], max_length=20)),
                ('contact_person', models.TextField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'account_type')},
            },
        ),
    ]
