# Generated by Django 4.2.16 on 2025-09-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address including street, city, state, country'),
        ),
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this account'),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.TextField(blank=True, help_text="Contact person's position/title (can be detailed)"),
        ),
    ]
