# Generated by Django 4.2.16 on 2025-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_enhanced_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, choices=[('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Medina', 'Medina'), ('Dammam', 'Dammam'), ('Khobar', 'Khobar'), ('Taif', 'Taif'), ('Mecca', 'Mecca'), ('Abha', 'Abha'), ('Tabuk', 'Tabuk'), ('Other', 'Other')], help_text='Primary city location', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_person',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
