# Generated by Django 5.2.6 on 2025-10-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_city_alter_account_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Company', 'Company'), ('Government', 'Government'), ('Travel Agency', 'Travel Agency'), ('Medical', 'Medical'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Education', 'Education'), ('Training and Consulting', 'Training and Consulting'), ('Hospitality', 'Hospitality'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Manufacturing', 'Manufacturing'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Other', 'Other')], max_length=30),
        ),
    ]
