# Generated by Django 5.2.6 on 2025-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_hardcoded_account_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, help_text='Primary city location', max_length=200),
        ),
    ]
