# Generated by Django 5.2.6 on 2025-10-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address including street, city, state, country', null=True),
        ),
    ]
