# Generated by Django 5.2.6 on 2025-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='business_card',
            field=models.FileField(blank=True, help_text='Business card attachment (PDF, JPG, PNG)', null=True, upload_to='business_cards/'),
        ),
    ]
