# Generated by Django 5.2.6 on 2025-10-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this account', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL', null=True),
        ),
    ]
