# Generated by Django 5.2.6 on 2025-10-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Reason description', max_length=200)),
                ('is_refundable', models.BooleanField(default=False, help_text='Allows refund')),
                ('active', models.BooleanField(default=True, help_text='Available for selection')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cancellation Reason',
                'verbose_name_plural': 'Cancellation Reasons',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
