# Generated by Django 5.2.6 on 2025-09-12 18:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Group Accommodation', 'Group Accommodation (10+ rooms)'), ('Individual Accommodation', 'Individual Accommodation (1-9 rooms)'), ('Event with Rooms', 'Event with Rooms'), ('Event without Rooms', 'Event without Rooms'), ('Series Group', 'Series Group (multiple dates)')], max_length=30)),
                ('confirmation_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('request_received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(blank=True, help_text='Automatically calculated', null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Draft', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Only required when status is Cancelled')),
                ('offer_acceptance_deadline', models.DateField(blank=True, null=True)),
                ('deposit_deadline', models.DateField(blank=True, null=True)),
                ('full_payment_deadline', models.DateField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('coffee_break_time', models.TimeField(blank=True, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('agenda_details', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_agendas', to='requests.request')),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='RoomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Superior', 'Superior'), ('Deluxe', 'Deluxe'), ('Executive', 'Executive'), ('Villa with Garden', 'Villa with Garden'), ('Villa with Pool', 'Villa with Pool')], max_length=20)),
                ('occupancy', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Twin', 'Twin')], max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_entries', to='requests.request')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesGroupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('group_size', models.PositiveIntegerField()),
                ('special_notes', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_entries', to='requests.request')),
            ],
            options={
                'ordering': ['arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='SeriesRoomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Superior', 'Superior'), ('Deluxe', 'Deluxe'), ('Executive', 'Executive'), ('Villa with Garden', 'Villa with Garden'), ('Villa with Pool', 'Villa with Pool')], max_length=20)),
                ('occupancy', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Twin', 'Twin')], max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('series_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_entries', to='requests.seriesgroupentry')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Van', 'Van'), ('Bus', 'Bus'), ('Limousine', 'Limousine'), ('Coach', 'Coach')], max_length=20)),
                ('number_of_pax', models.PositiveIntegerField(help_text='Number of passengers')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_entries', to='requests.request')),
            ],
        ),
    ]
