# Generated by Django 5.2.6 on 2025-09-12 19:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_request_confirmation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='meal_plan',
            field=models.CharField(choices=[('RO', 'Room Only'), ('BB', 'Bed & Breakfast'), ('HB', 'Half Board (Breakfast + Dinner)'), ('FB', 'Full Board (All Meals)')], default='RO', max_length=2),
        ),
        migrations.AddField(
            model_name='request',
            name='total_room_nights',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total room nights (rooms × nights)'),
        ),
        migrations.AddField(
            model_name='request',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of rooms across all entries'),
        ),
        migrations.AddField(
            model_name='seriesgroupentry',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Expected arrival time', null=True),
        ),
        migrations.AddField(
            model_name='seriesgroupentry',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Expected departure time', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Automatically calculated from room entries and transportation', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
