# Generated by Django 5.2.6 on 2025-09-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_meal_plan_request_total_room_nights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled Request',
                'verbose_name_plural': 'Cancelled Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='event_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='check_in_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='seriesgroupentry',
            name='arrival_date',
            field=models.DateField(db_index=True),
        ),
    ]
