# Generated by Django 5.2.6 on 2025-09-13 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_cancelledrequest_alter_eventagenda_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Reason description', max_length=200)),
                ('is_refundable', models.BooleanField(default=False, help_text='Allows refund')),
                ('active', models.BooleanField(default=True, help_text='Available for selection')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cancellation Reason',
                'verbose_name_plural': 'Cancellation Reasons',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RequestFormLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Group Accommodation', 'Group Accommodation'), ('Individual Accommodation', 'Individual Accommodation (1-9 rooms)'), ('Event with Rooms', 'Event with Rooms'), ('Event without Rooms', 'Event without Rooms'), ('Series Group', 'Series Group')], max_length=30, unique=True)),
                ('sections', models.JSONField(default=list, help_text="JSON array of sections: [{'name': 'Basic Info', 'fields': ['field1', 'field2'], 'order': 1}]")),
                ('active', models.BooleanField(default=True, help_text='Layout is active')),
                ('updated_by', models.CharField(blank=True, help_text='Last updated by', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Layout',
                'verbose_name_plural': 'Form Layouts',
                'ordering': ['request_type'],
            },
        ),
        migrations.CreateModel(
            name='RoomOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier (e.g., SGL, DBL)', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Display label (e.g., Single, Double)', max_length=100)),
                ('pax_count', models.PositiveIntegerField(help_text='Number of guests')),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('active', models.BooleanField(default=True, help_text='Available for selection')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Occupancy',
                'verbose_name_plural': 'Room Occupancies',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier (e.g., SUP, DLX)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g., Superior, Deluxe)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('active', models.BooleanField(default=True, help_text='Available for selection')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Custom cancellation reason (when fixed reason not sufficient)'),
        ),
        migrations.AddField(
            model_name='request',
            name='cancellation_reason_fixed',
            field=models.ForeignKey(blank=True, help_text='Select from predefined cancellation reasons', null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.cancellationreason'),
        ),
        migrations.CreateModel(
            name='RequestFieldRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Group Accommodation', 'Group Accommodation'), ('Individual Accommodation', 'Individual Accommodation (1-9 rooms)'), ('Event with Rooms', 'Event with Rooms'), ('Event without Rooms', 'Event without Rooms'), ('Series Group', 'Series Group')], max_length=30)),
                ('field_name', models.CharField(help_text='Django field name', max_length=100)),
                ('field_label', models.CharField(help_text='Display label', max_length=200)),
                ('required', models.BooleanField(default=False, help_text='Field is required')),
                ('enabled', models.BooleanField(default=True, help_text='Field is visible')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field Requirement',
                'verbose_name_plural': 'Field Requirements',
                'ordering': ['request_type', 'sort_order', 'field_name'],
                'unique_together': {('request_type', 'field_name')},
            },
        ),
        migrations.AddField(
            model_name='roomentry',
            name='occupancy_type',
            field=models.ForeignKey(blank=True, help_text='Select from admin-configured occupancy types', null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.roomoccupancy'),
        ),
        migrations.AddField(
            model_name='seriesroomentry',
            name='occupancy_type',
            field=models.ForeignKey(blank=True, help_text='Select from admin-configured occupancy types', null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.roomoccupancy'),
        ),
        migrations.AddField(
            model_name='roomentry',
            name='room_type',
            field=models.ForeignKey(blank=True, help_text='Select from admin-configured room types', null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.roomtype'),
        ),
        migrations.AddField(
            model_name='seriesroomentry',
            name='room_type',
            field=models.ForeignKey(blank=True, help_text='Select from admin-configured room types', null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.roomtype'),
        ),
    ]
