# Generated by Django 5.2.6 on 2025-09-13 19:47

from django.db import migrations


def populate_system_configuration(apps, schema_editor):
    """Populate system-wide configuration data for all modules"""
    # This migration will run after the models are created in migration 0008
    pass


def reverse_populate_system_configuration(apps, schema_editor):
    """Reverse the population of system configuration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_populate_configuration_data'),
    ]

    operations = [
        migrations.RunPython(
            populate_system_configuration,
            reverse_populate_system_configuration,
        ),
    ]
