# Generated by Django 5.2.6 on 2025-09-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_populate_system_configuration_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFieldRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('requests', 'Requests'), ('sales_calls', 'Sales Calls'), ('agreements', 'Agreements'), ('accounts', 'Accounts')], max_length=20)),
                ('form_type', models.CharField(choices=[('requests.Group Accommodation', 'Requests - Group Accommodation'), ('requests.Individual Accommodation', 'Requests - Individual Accommodation'), ('requests.Event with Rooms', 'Requests - Event with Rooms'), ('requests.Event without Rooms', 'Requests - Event without Rooms'), ('requests.Series Group', 'Requests - Series Group'), ('sales_calls.SalesCall', 'Sales Calls - Visit Form'), ('agreements.Agreement', 'Agreements - Agreement Form'), ('accounts.Account', 'Accounts - Account Form')], max_length=50)),
                ('field_name', models.CharField(help_text='Django field name', max_length=100)),
                ('field_label', models.CharField(help_text='Display label', max_length=200)),
                ('required', models.BooleanField(default=False, help_text='Field is required')),
                ('enabled', models.BooleanField(default=True, help_text='Field is visible')),
                ('section_name', models.CharField(default='Basic Information', help_text='Section/fieldset name', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within section')),
                ('help_text', models.TextField(blank=True, help_text='Custom help text for this field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Field Requirement',
                'verbose_name_plural': 'System Field Requirements',
                'ordering': ['module', 'form_type', 'section_name', 'sort_order', 'field_name'],
                'unique_together': {('form_type', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='SystemFormLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('requests', 'Requests'), ('sales_calls', 'Sales Calls'), ('agreements', 'Agreements'), ('accounts', 'Accounts')], max_length=20)),
                ('form_type', models.CharField(choices=[('requests.Group Accommodation', 'Requests - Group Accommodation'), ('requests.Individual Accommodation', 'Requests - Individual Accommodation'), ('requests.Event with Rooms', 'Requests - Event with Rooms'), ('requests.Event without Rooms', 'Requests - Event without Rooms'), ('requests.Series Group', 'Requests - Series Group'), ('sales_calls.SalesCall', 'Sales Calls - Visit Form'), ('agreements.Agreement', 'Agreements - Agreement Form'), ('accounts.Account', 'Accounts - Account Form')], max_length=50, unique=True)),
                ('sections', models.JSONField(default=list, help_text="JSON array of sections: [{'name': 'Basic Info', 'fields': ['field1', 'field2'], 'order': 1, 'collapsed': false}]")),
                ('active', models.BooleanField(default=True, help_text='Layout is active')),
                ('updated_by', models.CharField(blank=True, help_text='Last updated by', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Form Layout',
                'verbose_name_plural': 'System Form Layouts',
                'ordering': ['module', 'form_type'],
            },
        ),
        migrations.DeleteModel(
            name='RequestFieldRequirement',
        ),
        migrations.DeleteModel(
            name='RequestFormLayout',
        ),
        migrations.CreateModel(
            name='RequestFieldRequirement',
            fields=[
            ],
            options={
                'verbose_name': 'Request Field Requirement (Deprecated)',
                'verbose_name_plural': 'Request Field Requirements (Deprecated)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.systemfieldrequirement',),
        ),
        migrations.CreateModel(
            name='RequestFormLayout',
            fields=[
            ],
            options={
                'verbose_name': 'Request Form Layout (Deprecated)',
                'verbose_name_plural': 'Request Form Layouts (Deprecated)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.systemformlayout',),
        ),
    ]
