# Generated by Django 5.2.6 on 2025-09-13 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_populate_system_wide_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Model name (e.g., 'Invoice')", max_length=100, unique=True)),
                ('app_label', models.CharField(default='requests', help_text='Django app where model belongs', max_length=100)),
                ('table_name', models.CharField(help_text='Database table name', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name for admin', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of this model's purpose")),
                ('ordering_fields', models.JSONField(default=list, help_text='Fields to use for default ordering')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is active in the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Model',
                'verbose_name_plural': 'Dynamic Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicModelMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('operation_type', models.CharField(choices=[('create_model', 'Create Model'), ('add_field', 'Add Field'), ('remove_field', 'Remove Field'), ('alter_field', 'Alter Field'), ('delete_model', 'Delete Model')], max_length=20)),
                ('operation_data', models.JSONField(help_text='Serialized operation data for rollback')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dynamic Migration',
                'verbose_name_plural': 'Dynamic Migrations',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field name in database (lowercase, underscores)', max_length=100)),
                ('display_name', models.CharField(help_text='Label shown in forms', max_length=100)),
                ('field_type', models.CharField(choices=[('char', 'Text (Short)'), ('text', 'Text (Long)'), ('email', 'Email'), ('url', 'URL'), ('slug', 'Slug'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'Date & Time'), ('time', 'Time'), ('boolean', 'Checkbox (Yes/No)'), ('choice', 'Dropdown (Single Choice)'), ('multiple_choice', 'Multiple Choice'), ('file', 'File Upload'), ('image', 'Image Upload'), ('foreign_key', 'Link to Another Model'), ('many_to_many', 'Multiple Links'), ('json', 'JSON Data')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True, help_text='Default value (JSON format for complex types)')),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='For text fields', null=True)),
                ('max_digits', models.PositiveIntegerField(blank=True, help_text='For decimal fields', null=True)),
                ('decimal_places', models.PositiveIntegerField(blank=True, help_text='For decimal fields', null=True)),
                ('choices', models.JSONField(default=dict, help_text="For choice fields: {'value': 'display_name'}")),
                ('related_model', models.CharField(blank=True, help_text='Model to link to (app.Model)', max_length=100)),
                ('section', models.CharField(default='General', help_text='Form section this field belongs to', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within section')),
                ('is_active', models.BooleanField(default=True, help_text='Whether field is shown in forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='requests.dynamicmodel')),
            ],
            options={
                'verbose_name': 'Dynamic Field',
                'verbose_name_plural': 'Dynamic Fields',
                'ordering': ['model', 'section', 'order'],
                'unique_together': {('model', 'name')},
            },
        ),
    ]
