# Generated by Django 5.2.6 on 2025-09-13 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('requests', '0010_add_dynamic_model_infrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the model instance')),
                ('value_text', models.TextField(blank=True, help_text='For text, email, url, choice fields', null=True)),
                ('value_integer', models.IntegerField(blank=True, help_text='For integer fields', null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=10, help_text='For decimal fields', max_digits=20, null=True)),
                ('value_float', models.FloatField(blank=True, help_text='For float fields', null=True)),
                ('value_boolean', models.BooleanField(blank=True, help_text='For boolean fields', null=True)),
                ('value_date', models.DateField(blank=True, help_text='For date fields', null=True)),
                ('value_datetime', models.DateTimeField(blank=True, help_text='For datetime fields', null=True)),
                ('value_time', models.TimeField(blank=True, help_text='For time fields', null=True)),
                ('value_file', models.FileField(blank=True, help_text='For file fields', null=True, upload_to='dynamic_fields/')),
                ('value_json', models.JSONField(blank=True, help_text='For JSON and multiple choice fields', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='The model this value belongs to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field', models.ForeignKey(help_text='The dynamic field definition', on_delete=django.db.models.deletion.CASCADE, to='requests.dynamicfield')),
            ],
            options={
                'verbose_name': 'Dynamic Field Value',
                'verbose_name_plural': 'Dynamic Field Values',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='requests_dy_content_6b964c_idx'), models.Index(fields=['field'], name='requests_dy_field_i_ec813c_idx')],
                'unique_together': {('content_type', 'object_id', 'field')},
            },
        ),
    ]
