# Generated by Django 5.2.6 on 2025-09-13 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_add_dynamic_field_value_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal section name', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Display name shown to users', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Description of this section's purpose")),
                ('order', models.IntegerField(default=100, help_text='Display order')),
                ('is_core_section', models.BooleanField(default=False, help_text='True if this represents an existing admin model')),
                ('source_model', models.CharField(blank=True, help_text="Full model name (e.g. 'accounts.Account') for core sections", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Section',
                'verbose_name_plural': 'Dynamic Sections',
                'ordering': ['is_core_section', 'order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dynamicfield',
            options={'ordering': ['model', 'section', 'section_name', 'order'], 'verbose_name': 'Dynamic Field', 'verbose_name_plural': 'Dynamic Fields'},
        ),
        migrations.AlterUniqueTogether(
            name='dynamicfield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='is_core_field',
            field=models.BooleanField(default=False, help_text='True if this represents an existing model field'),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='section_name',
            field=models.CharField(default='General', help_text='Form section name for grouping (legacy field)', max_length=100),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='requests.dynamicmodel'),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='requests.dynamicsection'),
        ),
    ]
