# Generated by Django 4.2.16 on 2025-09-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_add_dynamic_section_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='core_mode',
            field=models.CharField(choices=[('override', 'Override Existing Field'), ('create', 'Create New Core Field')], default='override', help_text='Whether to override existing field or create new one', max_length=20),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='model_field_name',
            field=models.CharField(blank=True, help_text='Name of existing model field to override (required for override mode)', max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicfield',
            name='storage',
            field=models.CharField(choices=[('model_field', 'Store in Model Field'), ('value_store', 'Store in DynamicFieldValue')], default='value_store', help_text='Where to store field values', max_length=20),
        ),
    ]
