# Generated by Django 4.2.16 on 2025-09-15 13:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0013_add_core_field_creation_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='cost',
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='dinner_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='packages',
            field=models.CharField(blank=True, choices=[('coffee_only', 'Coffee Break only'), ('coffee_lunch', 'Coffee Break and lunch'), ('coffee_lunch_dinner', 'Coffee Break and Lunch and Dinner'), ('two_coffee', '2 Coffee Break'), ('two_coffee_meal', '2 Coffee Break and lunch or dinner')], help_text='Package selection for catering', max_length=20),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='rate_per_person',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per person for selected package', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='rental_fees_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily rental fees for venue', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='total_persons',
            field=models.PositiveIntegerField(default=0, help_text='Total number of attendees'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='cost_per_way',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per one-way trip', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='transportation',
            name='timing',
            field=models.TimeField(blank=True, help_text='Departure/pickup time', null=True),
        ),
    ]
