# Generated by Django 4.2.16 on 2025-09-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0015_backfill_room_fields'),
    ]

    operations = [
        # Remove old category field from RoomEntry
        migrations.RemoveField(
            model_name='roomentry',
            name='category',
        ),
        # Remove old occupancy field from RoomEntry
        migrations.RemoveField(
            model_name='roomentry',
            name='occupancy',
        ),
        # Remove old category field from SeriesRoomEntry
        migrations.RemoveField(
            model_name='seriesroomentry',
            name='category',
        ),
        # Remove old occupancy field from SeriesRoomEntry
        migrations.RemoveField(
            model_name='seriesroomentry',
            name='occupancy',
        ),
        # Alter room_type field in RoomEntry to be required
        migrations.AlterField(
            model_name='roomentry',
            name='room_type',
            field=models.ForeignKey(
                help_text='Select from admin-configured room types',
                on_delete=django.db.models.deletion.PROTECT,
                to='requests.roomtype'
            ),
        ),
        # Alter occupancy_type field in RoomEntry to be required
        migrations.AlterField(
            model_name='roomentry',
            name='occupancy_type',
            field=models.ForeignKey(
                help_text='Select from admin-configured occupancy types',
                on_delete=django.db.models.deletion.PROTECT,
                to='requests.roomoccupancy'
            ),
        ),
        # Alter room_type field in SeriesRoomEntry to be required
        migrations.AlterField(
            model_name='seriesroomentry',
            name='room_type',
            field=models.ForeignKey(
                help_text='Select from admin-configured room types',
                on_delete=django.db.models.deletion.PROTECT,
                to='requests.roomtype'
            ),
        ),
        # Alter occupancy_type field in SeriesRoomEntry to be required
        migrations.AlterField(
            model_name='seriesroomentry',
            name='occupancy_type',
            field=models.ForeignKey(
                help_text='Select from admin-configured occupancy types',
                on_delete=django.db.models.deletion.PROTECT,
                to='requests.roomoccupancy'
            ),
        ),
    ]