# Generated by Django 4.2.16 on 2025-09-16 12:41

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0016_remove_legacy_room_fields'),
    ]

    operations = [
        # Add new room configuration fields to SeriesGroupEntry
        migrations.AddField(
            model_name='seriesgroupentry',
            name='room_type',
            field=models.ForeignKey(
                help_text='Select from admin-configured room types',
                on_delete=django.db.models.deletion.PROTECT,
                to='requests.roomtype',
                default=1  # Temporary default, will be removed
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesgroupentry',
            name='occupancy_type',
            field=models.ForeignKey(
                help_text='Select from admin-configured occupancy types',
                on_delete=django.db.models.deletion.PROTECT,
                to='requests.roomoccupancy',
                default=1  # Temporary default, will be removed
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesgroupentry',
            name='number_of_rooms',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                default=1  # Temporary default, will be removed
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesgroupentry',
            name='rate_per_night',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                default=Decimal('0.00')  # Temporary default, will be removed
            ),
            preserve_default=False,
        ),
        # Remove old fields that are no longer needed
        migrations.RemoveField(
            model_name='seriesgroupentry',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='seriesgroupentry',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='seriesgroupentry',
            name='group_size',
        ),
        migrations.RemoveField(
            model_name='seriesgroupentry',
            name='special_notes',
        ),
    ]