# Generated by Django 4.2.16 on 2025-09-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_restructure_series_group_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Accommodation Request',
                'verbose_name_plural': 'Accommodation Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.CreateModel(
            name='EventOnlyRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Event Only Request',
                'verbose_name_plural': 'Event Only Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.CreateModel(
            name='EventWithRoomsRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Event with Accommodation',
                'verbose_name_plural': 'Events with Accommodation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.CreateModel(
            name='SeriesGroupRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Series Group Request',
                'verbose_name_plural': 'Series Group Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requests.request',),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='meeting_room_name',
            field=models.CharField(choices=[('All Halls', 'All Halls'), ('IKMA', 'IKMA'), ('HEGRA', 'HEGRA'), ('DADAN', 'DADAN'), ('AL JADIDA', 'AL JADIDA'), ('Board Room', 'Board Room'), ('Al Badiya', 'Al Badiya'), ('La Palma', 'La Palma')], default='All Halls', help_text='Meeting room for the event', max_length=20),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='style',
            field=models.CharField(choices=[('Classroom', 'Classroom'), ('Theatre', 'Theatre'), ('U Shape', 'U Shape'), ('Board', 'Board'), ('Banquet', 'Banquet'), ('Reception', 'Reception')], default='Classroom', help_text='Room setup style', max_length=15),
        ),
    ]
