# Generated by Django 5.2.6 on 2025-10-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0019_add_actual_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventagenda',
            name='event_name',
            field=models.CharField(blank=True, help_text='Event name', max_length=200),
        ),
    ]
