# Generated by Django 5.2.6 on 2025-10-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0020_eventagenda_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='invoice_1',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Invoice 1'),
        ),
        migrations.AddField(
            model_name='request',
            name='invoice_2',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Invoice 2'),
        ),
        migrations.AddField(
            model_name='request',
            name='invoice_3',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Invoice 3'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Group Accommodation', 'Group Accommodation'), ('Individual Accommodation', 'Individual Accommodation (1-9 rooms)'), ('Event with Rooms', 'Event with Rooms'), ('Event without Rooms', 'Event Only'), ('Series Group', 'Series Group')], max_length=30),
        ),
        migrations.AlterField(
            model_name='systemfieldrequirement',
            name='form_type',
            field=models.CharField(choices=[('requests.Group Accommodation', 'Requests - Group Accommodation'), ('requests.Individual Accommodation', 'Requests - Individual Accommodation'), ('requests.Event with Rooms', 'Requests - Event with Rooms'), ('requests.Event without Rooms', 'Requests - Event Only'), ('requests.Series Group', 'Requests - Series Group'), ('sales_calls.SalesCall', 'Sales Calls - Visit Form'), ('agreements.Agreement', 'Agreements - Agreement Form'), ('accounts.Account', 'Accounts - Account Form')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemformlayout',
            name='form_type',
            field=models.CharField(choices=[('requests.Group Accommodation', 'Requests - Group Accommodation'), ('requests.Individual Accommodation', 'Requests - Individual Accommodation'), ('requests.Event with Rooms', 'Requests - Event with Rooms'), ('requests.Event without Rooms', 'Requests - Event Only'), ('requests.Series Group', 'Requests - Series Group'), ('sales_calls.SalesCall', 'Sales Calls - Visit Form'), ('agreements.Agreement', 'Agreements - Agreement Form'), ('accounts.Account', 'Accounts - Account Form')], max_length=50, unique=True),
        ),
    ]
