# Generated by Django 5.2.6 on 2025-10-21 20:57

from django.db import migrations


def move_cancellation_reasons(apps, schema_editor):
    """Move CancellationReason data from requests to settings app"""
    # Get the old model from requests app
    OldCancellationReason = apps.get_model('requests', 'CancellationReason')
    # Get the new model from settings app
    NewCancellationReason = apps.get_model('settings', 'CancellationReason')
    
    # Copy all data from old to new
    for old_reason in OldCancellationReason.objects.all():
        NewCancellationReason.objects.create(
            id=old_reason.id,
            code=old_reason.code,
            label=old_reason.label,
            is_refundable=old_reason.is_refundable,
            active=old_reason.active,
            sort_order=old_reason.sort_order,
            created_at=old_reason.created_at,
            updated_at=old_reason.updated_at
        )


def reverse_move_cancellation_reasons(apps, schema_editor):
    """Reverse the data migration"""
    # This is a one-way migration, so we don't need to reverse it
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0021_request_invoice_1_request_invoice_2_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(move_cancellation_reasons, reverse_move_cancellation_reasons),
    ]
