# Generated by Django 5.2.6 on 2025-10-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0022_auto_20251021_2357'),
    ]

    operations = [
    ]
