# Generated by Django 5.2.6 on 2025-10-21 21:17

from django.db import migrations


def fix_foreign_key_constraint(apps, schema_editor):
    """Fix the foreign key constraint to point to settings_cancellationreason table"""
    with schema_editor.connection.cursor() as cursor:
        # Drop the old foreign key constraint
        cursor.execute("""
            ALTER TABLE requests_request 
            DROP CONSTRAINT IF EXISTS requests_request_cancellation_reason__dca82ae8_fk_requests_
        """)
        
        # Add the new foreign key constraint pointing to settings_cancellationreason
        cursor.execute("""
            ALTER TABLE requests_request 
            ADD CONSTRAINT requests_request_cancellation_reason_fixed_fk_settings_cancellationreason
            FOREIGN KEY (cancellation_reason_fixed_id) 
            REFERENCES settings_cancellationreason(id) 
            DEFERRABLE INITIALLY DEFERRED
        """)


def reverse_fix_foreign_key_constraint(apps, schema_editor):
    """Reverse the foreign key constraint fix"""
    with schema_editor.connection.cursor() as cursor:
        # Drop the new foreign key constraint
        cursor.execute("""
            ALTER TABLE requests_request 
            DROP CONSTRAINT IF EXISTS requests_request_cancellation_reason_fixed_fk_settings_cancellationreason
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0023_auto_20251022_0017'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_foreign_key_constraint, reverse_fix_foreign_key_constraint),
    ]
