# Generated by Django 5.2.6 on 2025-09-12 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('Corporate', 'Corporate'), ('Travel Agency', 'Travel Agency'), ('Group', 'Group'), ('Government', 'Government')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('return_deadline', models.DateField(help_text='Deadline for signed agreement return')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Signed', 'Signed'), ('Expired', 'Expired')], default='Draft', max_length=10)),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('account', 'rate_type', 'start_date')},
            },
        ),
    ]
