# Generated by Django 5.2.6 on 2025-10-06 21:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='coffee_break_time',
            field=models.TimeField(blank=True, help_text='Coffee break time', null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='dinner_time',
            field=models.TimeField(blank=True, help_text='Dinner time', null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='lunch_time',
            field=models.TimeField(blank=True, help_text='Lunch time', null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='packages',
            field=models.CharField(blank=True, choices=[('coffee_only', 'Coffee Break only'), ('coffee_lunch', 'Coffee Break and lunch'), ('coffee_lunch_dinner', 'Coffee Break and Lunch and Dinner'), ('two_coffee', '2 Coffee Break'), ('two_coffee_meal', '2 Coffee Break and lunch or dinner'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('lunch_dinner', 'Lunch and Dinner')], help_text='Package selection for catering', max_length=20),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='rate_per_person',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per person for selected package', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='rental_fees_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily rental fees for venue', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='style',
            field=models.CharField(choices=[('Classroom', 'Classroom'), ('Theatre', 'Theatre'), ('U Shape', 'U Shape'), ('Board', 'Board'), ('Banquet', 'Banquet'), ('Reception', 'Reception')], default='Classroom', help_text='Room setup style', max_length=15),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='total_persons',
            field=models.PositiveIntegerField(default=0, help_text='Total number of attendees'),
        ),
    ]
