# Generated by Django 5.2.6 on 2025-10-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_eventbooking_coffee_break_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Actual', 'Actual')], default='Draft', max_length=20),
        ),
    ]
