# Generated by Django 5.2.6 on 2025-10-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_alter_eventbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='deposit_deadline',
            field=models.DateField(blank=True, help_text='Deadline for deposit payment', null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='full_payment_deadline',
            field=models.DateField(blank=True, help_text='Deadline for full payment', null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='offer_acceptance_deadline',
            field=models.DateField(blank=True, help_text='Deadline for offer acceptance', null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='request_received_date',
            field=models.DateField(blank=True, help_text='Date when request was received', null=True),
        ),
    ]
